using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class InputScript : MonoBehaviour {
	
	public static string[,] gamepadInput = {
		{
			"Jump",
			null,
			null,
			"Cancel",
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			"Horizontal",
			"Vertical",
			"Mouse X",
			"Mouse Y",
			null,
			null
		},
		{
			"[One] X",
			"[One] Square",
			"[One] Triangle",
			"[One] Circle",
			"[One] L1",
			"[One] R1",
			"[One] L2",
			"[One] R2",
			"[One] Share",
			"[One] Options",
			"[One] L3",
			"[One] R3",
			"[One] PS",
			"[One] Touchpad",
			"[One] Left Horizontal",
			"[One] Left Vertical",
			"[One] Right Horizontal",
			"[One] Right Vertical",
			"[One] DPad Horizontal",
			"[One] DPad Vertical"
		},
		{
			"[Two] X",
			"[Two] Square",
			"[Two] Triangle",
			"[Two] Circle",
			"[Two] L1",
			"[Two] R1",
			"[Two] L2",
			"[Two] R2",
			"[Two] Share",
			"[Two] Options",
			"[Two] L3",
			"[Two] R3",
			"[Two] PS",
			"[Two] Touchpad",
			"[Two] Left Horizontal",
			"[Two] Left Vertical",
			"[Two] Right Horizontal",
			"[Two] Right Vertical",
			"[Two] DPad Horizontal",
			"[Two] DPad Vertical"
		},
		{
			"[Three] X",
			"[Three] Square",
			"[Three] Triangle",
			"[Three] Circle",
			"[Three] L1",
			"[Three] R1",
			"[Three] L2",
			"[Three] R2",
			"[Three] Share",
			"[Three] Options",
			"[Three] L3",
			"[Three] R3",
			"[Three] PS",
			"[Three] Touchpad",
			"[Three] Left Horizontal",
			"[Three] Left Vertical",
			"[Three] Right Horizontal",
			"[Three] Right Vertical",
			"[Three] DPad Horizontal",
			"[Three] DPad Vertical"
		},
		{
			"[Four] X",
			"[Four] Square",
			"[Four] Triangle",
			"[Four] Circle",
			"[Four] L1",
			"[Four] R1",
			"[Four] L2",
			"[Four] R2",
			"[Four] Share",
			"[Four] Options",
			"[Four] L3",
			"[Four] R3",
			"[Four] PS",
			"[Four] Touchpad",
			"[Four] Left Horizontal",
			"[Four] Left Vertical",
			"[Four] Right Horizontal",
			"[Four] Right Vertical",
			"[Four] DPad Horizontal",
			"[Four] DPad Vertical"
		}
	};

}
